FROM ubuntu
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
 && apt-get update && apt-get install -y \
 gnat-10-aarch64-linux-gnu \
 gprbuild \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
