FROM ghcr.io/thindil/tashy:8.6.11
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
 && apt-get update && apt-get dist-upgrade -y  && apt-get install -y libmagic-dev \
 libxmlada-schema9-dev \
 libxmlada-input9-dev \
 asis-programs \
 libncursesada7-dev \
 adacontrol \
 libcmark-dev \
 libaws19-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
