FROM debian:testing
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
 && dpkg --add-architecture arm64 \
 && apt-get update && apt-get dist-upgrade -y && apt-get install -y \
 gnat-9-aarch64-linux-gnu \
 gprbuild \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
