FROM debian:testing
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
 && dpkg --add-architecture armhf \
 && apt-get update && apt-get dist-upgrade -y && apt-get install -y \
 gnat-10-arm-linux-gnueabihf \
 gprbuild \
 tcl \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
